package com.juhao.murexide.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val md_theme_primary = Color(0xFF6750A4)
val md_theme_onPrimary = Color(0xFFFFFFFF)
val md_theme_primaryContainer = Color(0xFFEADDFF)
val md_theme_onPrimaryContainer = Color(0xFF21005D)
val md_theme_secondary = Color(0xFF625B71)
val md_theme_onSecondary = Color(0xFFFFFFFF)
val md_theme_secondaryContainer = Color(0xFFE8DEF8)
val md_theme_onSecondaryContainer = Color(0xFF1D192B)
val md_theme_tertiary = Color(0xFF7D5260)
val md_theme_onTertiary = Color(0xFFFFFFFF)
val md_theme_tertiaryContainer = Color(0xFFFFD8E4)
val md_theme_onTertiaryContainer = Color(0xFF31111D)
val md_theme_error = Color(0xFFB3261E)
val md_theme_onError = Color(0xFFFFFFFF)
val md_theme_errorContainer = Color(0xFFF9DEDC)
val md_theme_onErrorContainer = Color(0xFF410E0B)
val md_theme_background = Color(0xFFFEF7FF)
val md_theme_onBackground = Color(0xFF1D1B20)
val md_theme_surface = Color(0xFFFEF7FF)
val md_theme_onSurface = Color(0xFF1D1B20)
val md_theme_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_onSurfaceVariant = Color(0xFF49454F)
val md_theme_outline = Color(0xFF79747E)
val md_theme_outlineVariant = Color(0xFFCAC4D0)
val md_theme_surfaceTint = Color(0xFF6750A4)
val md_theme_inverseSurface = Color(0xFF322F35)
val md_theme_inverseOnSurface = Color(0xFFF5EFF7)
val md_theme_inversePrimary = Color(0xFFD0BCFF)
val md_theme_surfaceContainerHighest = Color(0xFFE6E0E9)
val md_theme_surfaceContainerHigh = Color(0xFFECE6F0)
val md_theme_surfaceContainer = Color(0xFFF2ECF7)
val md_theme_surfaceContainerLow = Color(0xFFF8F2FD)
val md_theme_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_primaryFixed = Color(0xFFEADDFF)
val md_theme_primaryFixedDim = Color(0xFFD0BCFF)
val md_theme_onPrimaryFixed = Color(0xFF21005D)
val md_theme_onPrimaryFixedVariant = Color(0xFF4F378B)
val md_theme_secondaryFixed = Color(0xFFE8DEF8)
val md_theme_secondaryFixedDim = Color(0xFFCCC2DC)
val md_theme_onSecondaryFixed = Color(0xFF1D192B)
val md_theme_onSecondaryFixedVariant = Color(0xFF4A4458)
val md_theme_tertiaryFixed = Color(0xFFFFD8E4)
val md_theme_tertiaryFixedDim = Color(0xFFEFB8C8)
val md_theme_onTertiaryFixed = Color(0xFF31111D)
val md_theme_onTertiaryFixedVariant = Color(0xFF633B48)
val md_theme_scrim = Color(0xFF000000)

// ===== Purple =====

val PurpleLightColorScheme = lightColorScheme(
    primary = Color(0xFF6750A4),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFEADDFF),
    onPrimaryContainer = Color(0xFF21005D),
    secondary = Color(0xFF625B71),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE8DEF8),
    onSecondaryContainer = Color(0xFF1D192B),
    tertiary = Color(0xFF7D5260),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD8E4),
    onTertiaryContainer = Color(0xFF31111D),
    error = Color(0xFFB3261E),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFF9DEDC),
    onErrorContainer = Color(0xFF410E0B),
    background = Color(0xFFFEF7FF),
    onBackground = Color(0xFF1D1B20),
    surface = Color(0xFFFEF7FF),
    onSurface = Color(0xFF1D1B20),
    surfaceVariant = Color(0xFFE7E0EC),
    onSurfaceVariant = Color(0xFF49454F),
    outline = Color(0xFF79747E),
    outlineVariant = Color(0xFFCAC4D0),
    surfaceTint = Color(0xFF6750A4),
    inverseSurface = Color(0xFF322F35),
    inverseOnSurface = Color(0xFFF5EFF7),
    inversePrimary = Color(0xFFD0BCFF),
    surfaceContainerHighest = Color(0xFFE6E0E9),
    surfaceContainerHigh = Color(0xFFECE6F0),
    surfaceContainer = Color(0xFFF2ECF7),
    surfaceContainerLow = Color(0xFFF8F2FD),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    primaryFixed = Color(0xFFEADDFF),
    primaryFixedDim = Color(0xFFD0BCFF),
    onPrimaryFixed = Color(0xFF21005D),
    onPrimaryFixedVariant = Color(0xFF4F378B),
    secondaryFixed = Color(0xFFE8DEF8),
    secondaryFixedDim = Color(0xFFCCC2DC),
    onSecondaryFixed = Color(0xFF1D192B),
    onSecondaryFixedVariant = Color(0xFF4A4458),
    tertiaryFixed = Color(0xFFFFD8E4),
    tertiaryFixedDim = Color(0xFFEFB8C8),
    onTertiaryFixed = Color(0xFF31111D),
    onTertiaryFixedVariant = Color(0xFF633B48),
    scrim = Color(0xFF000000)
)

val PurpleDarkColorScheme = darkColorScheme(
    primary = Color(0xFFD0BCFF),
    onPrimary = Color(0xFF381E72),
    primaryContainer = Color(0xFF4F378B),
    onPrimaryContainer = Color(0xFFEADDFF),
    secondary = Color(0xFFCCC2DC),
    onSecondary = Color(0xFF332D41),
    secondaryContainer = Color(0xFF4A4458),
    onSecondaryContainer = Color(0xFFE8DEF8),
    tertiary = Color(0xFFEFB8C8),
    onTertiary = Color(0xFF492532),
    tertiaryContainer = Color(0xFF633B48),
    onTertiaryContainer = Color(0xFFFFD8E4),
    error = Color(0xFFF2B8B5),
    onError = Color(0xFF601410),
    errorContainer = Color(0xFF8C1D18),
    onErrorContainer = Color(0xFFF9DEDC),
    background = Color(0xFF141218),
    onBackground = Color(0xFFE6E0E9),
    surface = Color(0xFF141218),
    onSurface = Color(0xFFE6E0E9),
    surfaceVariant = Color(0xFF49454F),
    onSurfaceVariant = Color(0xFFCAC4D0),
    outline = Color(0xFF938F99),
    outlineVariant = Color(0xFF49454F),
    surfaceTint = Color(0xFFD0BCFF),
    inverseSurface = Color(0xFFE6E0E9),
    inverseOnSurface = Color(0xFF322F35),
    inversePrimary = Color(0xFF6750A4),
    surfaceContainerHighest = Color(0xFF36343B),
    surfaceContainerHigh = Color(0xFF2B2930),
    surfaceContainer = Color(0xFF211F26),
    surfaceContainerLow = Color(0xFF1D1B20),
    surfaceContainerLowest = Color(0xFF0F0D13),
    primaryFixed = Color(0xFFEADDFF),
    primaryFixedDim = Color(0xFFD0BCFF),
    onPrimaryFixed = Color(0xFF21005D),
    onPrimaryFixedVariant = Color(0xFF4F378B),
    secondaryFixed = Color(0xFFE8DEF8),
    secondaryFixedDim = Color(0xFFCCC2DC),
    onSecondaryFixed = Color(0xFF1D192B),
    onSecondaryFixedVariant = Color(0xFF4A4458),
    tertiaryFixed = Color(0xFFFFD8E4),
    tertiaryFixedDim = Color(0xFFEFB8C8),
    onTertiaryFixed = Color(0xFF31111D),
    onTertiaryFixedVariant = Color(0xFF633B48),
    scrim = Color(0xFF000000)
)

// ===== Blue =====

val BlueLightColorScheme = lightColorScheme(
    primary = Color(0xFF5B8FA8),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFC8E6F0),
    onPrimaryContainer = Color(0xFF001F2A),
    secondary = Color(0xFF6B8F9E),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD0E8F2),
    onSecondaryContainer = Color(0xFF1A2F38),
    tertiary = Color(0xFF7A8FA0),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD8E6F0),
    onTertiaryContainer = Color(0xFF1E2A32),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF5FAFC),
    onBackground = Color(0xFF1A1C1E),
    surface = Color(0xFFF5FAFC),
    onSurface = Color(0xFF1A1C1E),
    surfaceVariant = Color(0xFFD8E4EC),
    onSurfaceVariant = Color(0xFF404850),
    outline = Color(0xFF707880),
    outlineVariant = Color(0xFFC0C8D0),
    surfaceTint = Color(0xFF5B8FA8),
    inverseSurface = Color(0xFF2F3133),
    inverseOnSurface = Color(0xFFEDF1F3),
    inversePrimary = Color(0xFFB0D0E0),
    surfaceContainerHighest = Color(0xFFDDE3E7),
    surfaceContainerHigh = Color(0xFFE3E9ED),
    surfaceContainer = Color(0xFFE9EFF2),
    surfaceContainerLow = Color(0xFFEFF4F7),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    primaryFixed = Color(0xFFC8E6F0),
    primaryFixedDim = Color(0xFFA0C8D8),
    onPrimaryFixed = Color(0xFF001F2A),
    onPrimaryFixedVariant = Color(0xFF2A5568),
    secondaryFixed = Color(0xFFD0E8F2),
    secondaryFixedDim = Color(0xFFB0C8D4),
    onSecondaryFixed = Color(0xFF1A2F38),
    onSecondaryFixedVariant = Color(0xFF3A5568),
    tertiaryFixed = Color(0xFFD8E6F0),
    tertiaryFixedDim = Color(0xFFB8C8D4),
    onTertiaryFixed = Color(0xFF1E2A32),
    onTertiaryFixedVariant = Color(0xFF405568),
    scrim = Color(0xFF000000)
)

val BlueDarkColorScheme = darkColorScheme(
    primary = Color(0xFFA0C8D8),
    onPrimary = Color(0xFF0A3545),
    primaryContainer = Color(0xFF2A5568),
    onPrimaryContainer = Color(0xFFC8E6F0),
    secondary = Color(0xFFB0C8D4),
    onSecondary = Color(0xFF1A3040),
    secondaryContainer = Color(0xFF3A5568),
    onSecondaryContainer = Color(0xFFD0E8F2),
    tertiary = Color(0xFFB8C8D4),
    onTertiary = Color(0xFF1E2A32),
    tertiaryContainer = Color(0xFF405568),
    onTertiaryContainer = Color(0xFFD8E6F0),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0F1418),
    onBackground = Color(0xFFE0E4E8),
    surface = Color(0xFF0F1418),
    onSurface = Color(0xFFE0E4E8),
    surfaceVariant = Color(0xFF404850),
    onSurfaceVariant = Color(0xFFC0C8D0),
    outline = Color(0xFF8A9298),
    outlineVariant = Color(0xFF404850),
    surfaceTint = Color(0xFFA0C8D8),
    inverseSurface = Color(0xFFE0E4E8),
    inverseOnSurface = Color(0xFF2F3133),
    inversePrimary = Color(0xFF5B8FA8),
    surfaceContainerHighest = Color(0xFF2E3337),
    surfaceContainerHigh = Color(0xFF23282C),
    surfaceContainer = Color(0xFF1A1F22),
    surfaceContainerLow = Color(0xFF151A1D),
    surfaceContainerLowest = Color(0xFF0A0E11),
    primaryFixed = Color(0xFFC8E6F0),
    primaryFixedDim = Color(0xFFA0C8D8),
    onPrimaryFixed = Color(0xFF001F2A),
    onPrimaryFixedVariant = Color(0xFF2A5568),
    secondaryFixed = Color(0xFFD0E8F2),
    secondaryFixedDim = Color(0xFFB0C8D4),
    onSecondaryFixed = Color(0xFF1A2F38),
    onSecondaryFixedVariant = Color(0xFF3A5568),
    tertiaryFixed = Color(0xFFD8E6F0),
    tertiaryFixedDim = Color(0xFFB8C8D4),
    onTertiaryFixed = Color(0xFF1E2A32),
    onTertiaryFixedVariant = Color(0xFF405568),
    scrim = Color(0xFF000000)
)

// ===== Green =====

val GreenLightColorScheme = lightColorScheme(
    primary = Color(0xFF386A20),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFB8F397),
    onPrimaryContainer = Color(0xFF042100),
    secondary = Color(0xFF55624C),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD8E7CB),
    onSecondaryContainer = Color(0xFF131F0D),
    tertiary = Color(0xFF386667),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBBEBEC),
    onTertiaryContainer = Color(0xFF002020),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFDFDF5),
    onBackground = Color(0xFF1A1C18),
    surface = Color(0xFFFDFDF5),
    onSurface = Color(0xFF1A1C18),
    surfaceVariant = Color(0xFFDFE4D7),
    onSurfaceVariant = Color(0xFF43483E),
    outline = Color(0xFF73796D),
    outlineVariant = Color(0xFFC3C8BB),
    surfaceTint = Color(0xFF386A20),
    inverseSurface = Color(0xFF2F312D),
    inverseOnSurface = Color(0xFFEDEEE6),
    inversePrimary = Color(0xFF9CD67D),
    surfaceContainerHighest = Color(0xFFDCE0D6),
    surfaceContainerHigh = Color(0xFFE2E6DC),
    surfaceContainer = Color(0xFFE8ECE2),
    surfaceContainerLow = Color(0xFFEEF2E8),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    primaryFixed = Color(0xFFB8F397),
    primaryFixedDim = Color(0xFF9CD67D),
    onPrimaryFixed = Color(0xFF042100),
    onPrimaryFixedVariant = Color(0xFF1F5108),
    secondaryFixed = Color(0xFFD8E7CB),
    secondaryFixedDim = Color(0xFFBCCBB1),
    onSecondaryFixed = Color(0xFF131F0D),
    onSecondaryFixedVariant = Color(0xFF3D4B36),
    tertiaryFixed = Color(0xFFBBEBEC),
    tertiaryFixedDim = Color(0xFFA0CFD0),
    onTertiaryFixed = Color(0xFF002020),
    onTertiaryFixedVariant = Color(0xFF1E4E4F),
    scrim = Color(0xFF000000)
)

val GreenDarkColorScheme = darkColorScheme(
    primary = Color(0xFF9CD67D),
    onPrimary = Color(0xFF0A3900),
    primaryContainer = Color(0xFF1F5108),
    onPrimaryContainer = Color(0xFFB8F397),
    secondary = Color(0xFFBCCBB1),
    onSecondary = Color(0xFF273420),
    secondaryContainer = Color(0xFF3D4B36),
    onSecondaryContainer = Color(0xFFD8E7CB),
    tertiary = Color(0xFFA0CFD0),
    onTertiary = Color(0xFF003738),
    tertiaryContainer = Color(0xFF1E4E4F),
    onTertiaryContainer = Color(0xFFBBEBEC),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1A1C18),
    onBackground = Color(0xFFE2E3DB),
    surface = Color(0xFF1A1C18),
    onSurface = Color(0xFFE2E3DB),
    surfaceVariant = Color(0xFF43483E),
    onSurfaceVariant = Color(0xFFC3C8BB),
    outline = Color(0xFF8D9387),
    outlineVariant = Color(0xFF43483E),
    surfaceTint = Color(0xFF9CD67D),
    inverseSurface = Color(0xFFE2E3DB),
    inverseOnSurface = Color(0xFF2F312D),
    inversePrimary = Color(0xFF386A20),
    surfaceContainerHighest = Color(0xFF353731),
    surfaceContainerHigh = Color(0xFF292C27),
    surfaceContainer = Color(0xFF1F211D),
    surfaceContainerLow = Color(0xFF1A1C18),
    surfaceContainerLowest = Color(0xFF0F110E),
    primaryFixed = Color(0xFFB8F397),
    primaryFixedDim = Color(0xFF9CD67D),
    onPrimaryFixed = Color(0xFF042100),
    onPrimaryFixedVariant = Color(0xFF1F5108),
    secondaryFixed = Color(0xFFD8E7CB),
    secondaryFixedDim = Color(0xFFBCCBB1),
    onSecondaryFixed = Color(0xFF131F0D),
    onSecondaryFixedVariant = Color(0xFF3D4B36),
    tertiaryFixed = Color(0xFFBBEBEC),
    tertiaryFixedDim = Color(0xFFA0CFD0),
    onTertiaryFixed = Color(0xFF002020),
    onTertiaryFixedVariant = Color(0xFF1E4E4F),
    scrim = Color(0xFF000000)
)

// ===== Orange =====

val OrangeLightColorScheme = lightColorScheme(
    primary = Color(0xFF9C4208),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDBCA),
    onPrimaryContainer = Color(0xFF341100),
    secondary = Color(0xFF765848),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDBCA),
    onSecondaryContainer = Color(0xFF2B160A),
    tertiary = Color(0xFF636032),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFE9E5AA),
    onTertiaryContainer = Color(0xFF1E1C00),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFFBFF),
    onBackground = Color(0xFF201A16),
    surface = Color(0xFFFFFBFF),
    onSurface = Color(0xFF201A16),
    surfaceVariant = Color(0xFFF4DED4),
    onSurfaceVariant = Color(0xFF52443B),
    outline = Color(0xFF84746A),
    outlineVariant = Color(0xFFD7C3B7),
    surfaceTint = Color(0xFF9C4208),
    inverseSurface = Color(0xFF362F2B),
    inverseOnSurface = Color(0xFFFBEEE7),
    inversePrimary = Color(0xFFFFB68C),
    surfaceContainerHighest = Color(0xFFE8DCD5),
    surfaceContainerHigh = Color(0xFFEEE2DB),
    surfaceContainer = Color(0xFFF4E8E1),
    surfaceContainerLow = Color(0xFFFAEEE7),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    primaryFixed = Color(0xFFFFDBCA),
    primaryFixedDim = Color(0xFFFFB68C),
    onPrimaryFixed = Color(0xFF341100),
    onPrimaryFixedVariant = Color(0xFF773100),
    secondaryFixed = Color(0xFFFFDBCA),
    secondaryFixedDim = Color(0xFFE6BDA9),
    onSecondaryFixed = Color(0xFF2B160A),
    onSecondaryFixedVariant = Color(0xFF5C4132),
    tertiaryFixed = Color(0xFFE9E5AA),
    tertiaryFixedDim = Color(0xFFCDC990),
    onTertiaryFixed = Color(0xFF1E1C00),
    onTertiaryFixedVariant = Color(0xFF4B491E),
    scrim = Color(0xFF000000)
)

val OrangeDarkColorScheme = darkColorScheme(
    primary = Color(0xFFFFB68C),
    onPrimary = Color(0xFF552000),
    primaryContainer = Color(0xFF773100),
    onPrimaryContainer = Color(0xFFFFDBCA),
    secondary = Color(0xFFE6BDA9),
    onSecondary = Color(0xFF432B1D),
    secondaryContainer = Color(0xFF5C4132),
    onSecondaryContainer = Color(0xFFFFDBCA),
    tertiary = Color(0xFFCDC990),
    onTertiary = Color(0xFF333108),
    tertiaryContainer = Color(0xFF4B491E),
    onTertiaryContainer = Color(0xFFE9E5AA),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF201A16),
    onBackground = Color(0xFFECE0DA),
    surface = Color(0xFF201A16),
    onSurface = Color(0xFFECE0DA),
    surfaceVariant = Color(0xFF52443B),
    onSurfaceVariant = Color(0xFFD7C3B7),
    outline = Color(0xFFA08D82),
    outlineVariant = Color(0xFF52443B),
    surfaceTint = Color(0xFFFFB68C),
    inverseSurface = Color(0xFFECE0DA),
    inverseOnSurface = Color(0xFF362F2B),
    inversePrimary = Color(0xFF9C4208),
    surfaceContainerHighest = Color(0xFF3A322D),
    surfaceContainerHigh = Color(0xFF2E2723),
    surfaceContainer = Color(0xFF231D19),
    surfaceContainerLow = Color(0xFF201A16),
    surfaceContainerLowest = Color(0xFF140F0C),
    primaryFixed = Color(0xFFFFDBCA),
    primaryFixedDim = Color(0xFFFFB68C),
    onPrimaryFixed = Color(0xFF341100),
    onPrimaryFixedVariant = Color(0xFF773100),
    secondaryFixed = Color(0xFFFFDBCA),
    secondaryFixedDim = Color(0xFFE6BDA9),
    onSecondaryFixed = Color(0xFF2B160A),
    onSecondaryFixedVariant = Color(0xFF5C4132),
    tertiaryFixed = Color(0xFFE9E5AA),
    tertiaryFixedDim = Color(0xFFCDC990),
    onTertiaryFixed = Color(0xFF1E1C00),
    onTertiaryFixedVariant = Color(0xFF4B491E),
    scrim = Color(0xFF000000)
)